apiVersion: v1
kind: Pod
metadata:
  name: my-containers  
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  
  containers:
  
  - name: container1
    image: nginx    
    volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html
  
  - name: container2
    image: debian
    volumeMounts:
      - name: shared-data
        mountPath: /pod-data
    command: ["/bin/sh"]
    args:
      - "-c"
      - >
        while true; do          
        date >> /pod-data/index.html;          
        echo This is Container2 you are on Container1 
        >> /pod-data/index.html;
        sleep 10; 
        done

